### ISSUE TITLE
Regenerating spawn "island"

### ISSUE THREAD

**Issue by cda94581** [SmokeyStack/smokey_skyblock#1]
The first 5 minutes of a new world are spent letting the world generate and creating a spawn island, which is what I believe is intended. However, this comes with a (potentially?) unintended consequence.

The way it was setup, _whenever_ the world is reloaded, the 5 minute timer starts. Because of that, once the players have already survived their first 5 minutes of being "safe", they're free to move about, and that also includes destroying the grass/nylium/saplings that are currently present, causing it to regenerate for 5 minutes.

Because I know you've been evil to us already, I don't believe this was intentional, so I'll just file this now.

**Comment by SmokeyStack** [comment]
Fixed with v1.1.0
